name: Build OpenTelemetry Collector Contrib

on:
  workflow_dispatch:
    inputs:
      architectures:
        description: 'Architectures to build (comma-separated)'
        required: true
        default: 'amd64'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true

    - name: Set lowercase owner
      id: lowercase
      run: |
        echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Set architectures
      id: set-archs
      run: |
        ARCHS="${{ github.event.inputs.architectures || 'amd64,arm64' }}"
        echo "archs=$ARCHS" >> $GITHUB_OUTPUT
        echo "platforms=$(echo $ARCHS | sed 's/,/,linux\//g' | sed 's/^/linux\//')" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for GHCR
      id: meta-ghcr
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol
        tags: |
          type=sha,format=long
          type=ref,event=branch
          type=ref,event=tag
          latest

    - name: Extract metadata for Docker Hub
      id: meta-dockerhub
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/otelcontribcol
        tags: |
          type=sha,format=long
          type=ref,event=branch
          type=ref,event=tag
          latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build OpenTelemetry Collector Contrib
      run: |
        for arch in $(echo "${{ steps.set-archs.outputs.archs }}" | tr ',' ' '); do
          GOOS=linux GOARCH=$arch COMPONENT=otelcontribcol make otelcontribcol
        done

    - name: Prepare Docker build context
      run: |
        for arch in $(echo "${{ steps.set-archs.outputs.archs }}" | tr ',' ' '); do
          cp ./bin/otelcontribcol_linux_$arch ./cmd/otelcontribcol/otelcontribcol_$arch
        done

    - name: Push to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./cmd/otelcontribcol
        push: true
        platforms: ${{ steps.set-archs.outputs.platforms }}
        tags: ${{ steps.meta-ghcr.outputs.tags }}
        labels: ${{ steps.meta-ghcr.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol:buildcache,mode=max

    - name: Push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./cmd/otelcontribcol
        push: true
        platforms: ${{ steps.set-archs.outputs.platforms }}
        tags: ${{ steps.meta-dockerhub.outputs.tags }}
        labels: ${{ steps.meta-dockerhub.outputs.labels }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/otelcontribcol:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/otelcontribcol:buildcache,mode=max