name: Build OpenTelemetry Collector Contrib

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
    
    - name: Set lowercase owner
      id: lowercase
      run: |
        echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol
        tags: |
          type=sha,format=long
          type=ref,event=branch
          type=ref,event=tag
          latest
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build OpenTelemetry Collector Contrib
      run: |
        # Build the binary for the base architecture needed for Docker build
        COMPONENT=otelcontribcol make otelcontribcol
        
    - name: Build and push Docker image with Buildx
      id: push
      uses: docker/build-push-action@v4
      with:
        context: ./cmd/otelcontribcol
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol:buildcache,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ steps.lowercase.outputs.owner }}/otelcontribcol
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
